# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ber_gui.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
#from litex.soc.tools.remote import RemoteClient
#from control_prbs import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 20, 541, 213))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 1, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_5, 2, 3, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_6, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 7, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 7, 3, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 5, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 5, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 5, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 6, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 1, 3, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 6, 2, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 7, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 6, 3, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 3, 2, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 3, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "TX PRBS Config"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "PRBS7"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "PRBS15"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "PRBS23"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "PRBS31"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "0%"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "25%"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "50%"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "75%"))
        self.comboBox_6.setItemText(4, _translate("MainWindow", "100%"))
        self.label_5.setText(_translate("MainWindow", "Bit Error Ratio"))
        self.label_14.setText(_translate("MainWindow", "ber"))
        self.comboBox.setItemText(0, _translate("MainWindow", "PRBS7"))
        self.comboBox.setItemText(1, _translate("MainWindow", "PRBS15"))
        self.comboBox.setItemText(2, _translate("MainWindow", "PRBS23"))
        self.comboBox.setItemText(3, _translate("MainWindow", "PRBS31"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "0%"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "25%"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "50%"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "75%"))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "100%"))
        self.label.setText(_translate("MainWindow", "8b10b Encoding"))
        self.pushButton_3.setText(_translate("MainWindow", "Enable"))
        self.pushButton.setText(_translate("MainWindow", "Enable"))
        self.label_3.setText(_translate("MainWindow", "Inject Error"))
        self.label_11.setText(_translate("MainWindow", "Link"))
        self.label_13.setText(_translate("MainWindow", "GTP2"))
        self.label_15.setText(_translate("MainWindow", "Link"))
        self.label_12.setText(_translate("MainWindow", "GTP1"))
        self.label_4.setText(_translate("MainWindow", "ber"))
        self.label_16.setText(_translate("MainWindow", "No Link"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "PRBS7"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "PRBS15"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "PRBS23"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "PRBS31"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "PRBS7"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "PRBS15"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "PRBS23"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "PRBS31"))
        self.label_6.setText(_translate("MainWindow", "RX PRBS Config"))

        self.comboBox.activated.connect(self.handleActivated)

    def handleActivated(self,index):
        print(self.comboBox.itemText(index))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

